# Stage 1: Build stage
FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Stage 2: Final production stage
FROM python:3.11-slim AS production

WORKDIR /app

COPY --from=builder /root/.cache/pip /root/.cache/pip
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
