controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: "lts"
  admin:
    username: "admin"  # ✅ Correct field name
    password: "admin"  # Change this in production!
  service:
    type: ClusterIP  # Use LoadBalancer if exposing externally
  persistence:
    enabled: true
    size: 8Gi

