apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'vigneshvp.20@gmail.com'
      smtp_auth_username: 'Suma@1981'
      smtp_auth_password: 'Suma@1981'
      smtp_require_tls: true

    route:
      receiver: "email-alert"

    receivers:
      - name: "email-alert"
        email_configs:
          - to: "vigneshvp.19@gmail.com"
            send_resolved: true

