apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        command: ["stress"]
        args: ["--cpu", "2", "--timeout", "300"]

