apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jenkins
spec:
  selector:
    app: django-backend
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 8000  
  type: LoadBalancer  

