apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: jenkins
spec:
  selector:
    app: nextjs-frontend
  ports:
    - protocol: TCP
      port: 80    # Publicly exposed port
      targetPort: 3000  # Next.js runs on port 3000
  type: LoadBalancer

