apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-frontend
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-frontend
  template:
    metadata:
      labels:
        app: menu-frontend
    spec:
      containers:
        - name: menu-frontend
          image: vgnsh/menu-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nextjs-config  # ✅ Inject API URL from ConfigMap
