apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-frontend
  namespace: jenkins
spec:
  template:
    spec:
      containers:
      - name: menu-frontend
        env:
        - name: NEXT_PUBLIC_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: nextjs-config
              key: NEXT_PUBLIC_API_BASE_URL
  