apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-frontend
  template:
    metadata:
      labels:
        app: menu-frontend
    spec:
      containers:
        - name: menu-frontend
          image: vgnsh/menu-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://localhost/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: menu-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32006  # Assigning NodePort manually
  type: NodePort  # Changing from ClusterIP to NodePort


