apiVersion: v1
kind: Service
metadata:
  name: django-backend
  namespace: jenkins
spec:
  selector:
    app: django-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32002  # Change if needed

