name: Django Backend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "menu/**"
  pull_request:
    branches:
      - master
    paths:
      - "menu/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -f Dockerfile.backend -t vgnsh/django-backend:latest .
          docker push vgnsh/django-backend:latest

      - name: Set up K3s CLI
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy Backend to K3s
        run: |
          kubectl rollout restart deployment django-backend -n default

