name: Next.js Frontend CI/CD

on:
  push:
    branches:
      - master  # Trigger workflow on push to master branch
    paths:
      - "menu-frontend/**"  # Only trigger on changes inside the 'menu-frontend' directory
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting master
    paths:
      - "menu-frontend/**"  # Only trigger for changes inside the 'menu-frontend' directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t vgnsh/menu-frontend:latest ./menu-frontend  # Building the Docker image
          docker push vgnsh/menu-frontend:latest  # Pushing the image to Docker Hub

      - name: Set up K3s CLI
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig  # Decode Kubeconfig and save
          export KUBECONFIG=kubeconfig  # Set KUBECONFIG for kubectl

      - name: Deploy Frontend to K3s
        run: |
          kubectl rollout restart deployment menu-frontend -n default  # Restart the deployment in K3s

